$('.owl-carousel').owlCarousel({
    loop:true,
    nav: false,
    margin:5,
    responsiveClass:true,
    responsive:{
        0:{
            items:1,
        },
        600:{
            items:1,
        },
        1000:{
            items:4,
            nav:true,
            loop:false
        }
    }
})